### ISSUE TITLE
Your Batch Size?

### ISSUE THREAD

**Issue by yueatsprograms** [facebook/fb.resnet.torch#10]
Hey Sam,

We are trying to use your code from https://github.com/facebook/fb.resnet.torch to train a 152 layer model on 4 Titan X GPUs. With a batch size of 256, we seem to get memory outage with the 152 layer model, and with a batch size of 128, it seems to just fit, each GPU taken up to 11.9 GB. I thought your code would be able to do batch size 256 with 4 GPUs?

We’d really appreciate your help!

Yu

**Comment by colesbury** [comment]
I'm using batch size 128 when training ResNet-152

**Comment by yueatsprograms** [comment]
Thanks a lot! @colesbury 
I would suggest the you change the following paragraph in your blog to avoid confusion from other folks.
<img width="848" alt="screen shot 2016-02-22 at 1 45 50 pm" src="https://cloud.githubusercontent.com/assets/5546216/13228569/b6f47112-d96a-11e5-95d4-594c291de93b.png">

**Comment by soumith** [comment]
fixed the language in the blogpost. Thanks.
