### ISSUE TITLE
Training on non-first GPU

### ISSUE THREAD

**Issue by ibmua** [facebook/fb.resnet.torch#105]
How to run this thing on a GPU that's not the first one? I want to run several trainers at once on different GPUs, which is kind of a much better idea than paralleling same model across GPUs if one actually wants to try different models, or hyperparams, especially if GPUs are not the same.

**Comment by huxuan** [comment]
`cutorch.setDevice(i)`

https://github.com/torch/cutorch#cutorch-api

**Comment by ibmua** [comment]
Thanks! I've tried that previously, but I probably made some error, so it didn't seem to work. So I tried again now and it worked fine. =)

**Comment by taineleau** [comment]
Hi, @ibmua 

The most favorable way is simply set the environment variable  `CUDA_VISIBLE_DEVICES`.

e.g.

```export CUDA_VISIBLE_DEVICES=1```

or

```export CUDA_VISIBLE_DEVICES=2,3```

**Comment by colesbury** [comment]
As @taineleau wrote, use the `CUDA_VISIBLE_DEVICES` environment variable. You'll run into fewer problems than if you use cutorch.setDevice

**Comment by ibmua** [comment]
Thanks for the hint!
