### ISSUE TITLE
Weight initialization: nOutputPlane or nInputPlane?

### ISSUE THREAD

**Issue by liuzhuang13** [facebook/fb.resnet.torch#106]
Hi,

In the resnet and pre-resnet model files, convolutional weights are initialized by
`local n = v.kW*v.kH*v.nOutputPlane` 
` v.weight:normal(0,math.sqrt(2/n))`
This is very similar to the so called 'msra' init method. However there is one important difference, in the original paper (https://arxiv.org/pdf/1502.01852v1.pdf), when calculating the variable "n" they actually use nInputPlane instead of nOutputPlane. And in most other implementations people are also using the 'msra' init method, i.e., using nInputPlane. So why choose to use nOutputPlane instead of nInputPlane?

Thanks!

**Comment by szagoruyko** [comment]
@liuzhuang13 there should be nInputPlane indeed. We tested this a while ago, it doesn't affect CIFAR results (with wide networks at least, haven't tested 1001), and doesn't affect ResNet-18-ResNet-34, but ResNet-50 and ResNet-101 seem to benefit a little bit from the correct init.

**Comment by liuzhuang13** [comment]
Ok, that's good to know, thanks!

**Comment by KaimingHe** [comment]
The paper (https://arxiv.org/pdf/1502.01852v1.pdf) has two ways of init: either with nOutputPlane or with nInputPlane. Using nInputPlane it keeps the backward magnitude, and nOutputPlane it keeps the forward magnitude, under the assumption of a plain network. ResNet does not satisfy this assumption, except for the layers inside a single block. The ResNet paper uses nOutputPlane.

**Comment by liuzhuang13** [comment]
@KaimingHe Thanks for your clarification! Very helpful. I guess I'm too careless when reading the paper https://arxiv.org/pdf/1502.01852v1.pdf, sorry!
