### ISSUE TITLE
shareGradInput Problem

### ISSUE THREAD

**Issue by yueatsprograms** [facebook/fb.resnet.torch#11]
Hi,

Thanks a lot for sharing your code, first of all! 

We found that using shareGradInput vs. not yield quite different results on cifar10. sharedGradInput tends to do significantly worse than not (and than the results we would expect). Here is a plot running your original code with the default settings on cifar10 with 4 GPUs, and shareGradInput=true vs. shareGradInput=false. This trend is verified in the 110 layer net, with true->9.61, false->6.84 %.

![unknown](https://cloud.githubusercontent.com/assets/5546216/13290095/63bd28d2-dae0-11e5-8789-00fcef221d6b.png)

We suspect that there's a bug in shareGradInput, would you please take a look?

**Comment by colesbury** [comment]
You may have to update and rebuild the nn package. There was a commit a few days ago that I had forgot about:
https://github.com/torch/nn/commit/69b2dff62e026a07cd56c76408e653fb9dee0b9d

**Comment by yueatsprograms** [comment]
Yes, that does it!
I'd highly recommend you noting that on your Github, a lot of people like me would spend weeks running ImageNet and finding the results below expectation, not knowing that this is the problem.
