### ISSUE TITLE
the classify result for resnet-50

### ISSUE THREAD

**Issue by laoreja** [facebook/fb.resnet.torch#118]
Hi there,

I found that the classification results of the model resnet-50 is always the same. Besides, I extracted the last layer for two images of different categories, but the two features are the same. The top-1 classification results are always the sunglass.

Then I tried to classify using my retrained model (based on resnet-50). This time, the probability varies, but the top-1 results are the same for all images.

So I guess there is something wrong?

**Comment by colesbury** [comment]
Are you using the pretrained ResNet-50 model from here?
https://github.com/facebook/fb.resnet.torch/tree/master/pretrained

Are you using classify.lua or some other way to classify your images?
