### ISSUE TITLE
Suggestions on nThreads

### ISSUE THREAD

**Issue by yueatsprograms** [facebook/fb.resnet.torch#12]
Do you have any insight on how to select the parameter nThreads?
I'm using a server with 2 10-corse CPUs and 4 Titan Xs that would be dedicated to running this code.

Thanks!

**Comment by colesbury** [comment]
Try `-nThreads 12`. When you run `main.lua` you'll see output that looks like the following:

```
=> Training epoch # 1
 | Epoch: [1][1/5005]    Time 17.392  Data 5.475  Err 7.1076  top1  99.219  top5  98.047
 | Epoch: [1][2/5005]    Time 0.810  Data 0.004  Err 7.1408  top1 100.000  top5 100.000
 | Epoch: [1][3/5005]    Time 0.945  Data 0.001  Err 7.1458  top1 100.000  top5 100.000
 | Epoch: [1][4/5005]    Time 0.945  Data 0.001  Err 7.0520  top1 100.000  top5  99.609
```

The `Data` column is the data loading time. If it's more than a few milliseconds after the first mini-batch, try increasing the number of data loading threads. If it's still more than a few milliseconds, buy an SSD :smiley:

**Comment by colesbury** [comment]
Oh, you may also want to run with the environment variable `OMP_NUM_THREADS=1`. Sometimes, especially on multi-socket machines, the overhead of OpenMP isn't worth it when using multiple data loading threads.

**Comment by yueatsprograms** [comment]
Thanks!
