### ISSUE TITLE
Is there any way to predict(classify) large amount of image?

### ISSUE THREAD

**Issue by Laodax** [facebook/fb.resnet.torch#121]
I want to predict more than thounds of or ten thounds of image, and I just know use like this"th classify.lua resnet-101.t7 img1.jpg img2.jpg ..."to input image. Can I input like a .txt file or any way to input a lot of image?

**Comment by colesbury** [comment]
The `classify.lua` script is not written to efficient classify lots of images since it does it one at a time. You can look at `extract-features.lua` which takes a directory of image for an example of how to handle lots of images at once.
