### ISSUE TITLE
Given  a new image of my own, in size H*W, I want to caluculate every output feature map's  size of the layers in resnet, but I can not find the specific parameters of every layer

### ISSUE THREAD

**Issue by brisker** [facebook/fb.resnet.torch#132]
So where to get information like this: 

![image](https://cloud.githubusercontent.com/assets/13804492/20391840/1c353aa6-ad10-11e6-97be-9c50efff605d.png)

What I want is the output size  information for Resnet, but I can not find every specific layer's parameters to calculate it myself , and can not find existing figures like above too

**Comment by colesbury** [comment]
Some of this information may be in http://arxiv.org/abs/1512.03385. You can also load a model, evaluate an image, and examine `layer.output:size()` for each layer in the model

**Comment by brisker** [comment]
@colesbury 
I tried to list all the layers of resnet , why there is just nothing displaying after I run the following code??
model=torch.load('/home/jcc/code/models/resnet-18.t7')
model:listModules()

**Comment by colesbury** [comment]
The dot file is really confusing. Page 4 in the ResNet paper is a good resource. Also, load the model in Torch and play around with it:

https://gist.github.com/colesbury/5d161bc96d72ff5083a3c405ea7d6d61
