### ISSUE TITLE
Training a Pre-trained model

### ISSUE THREAD

**Issue by ahmerlums** [facebook/fb.resnet.torch#136]
I have a pretrained model which say has 10 classes. Now I need to add 2 more classes to this model. So I need to retrain the model. But at the end I want the Classifier to recognize all 12 classes and I don't want to feed the old dataset each and every time due to speed constraint. Now when I retrain my old data set using "th main.lua -retrain model resetClassifier true -data [dataset] -nEpochs 10 -depth 18", the resulting model I get only recognizes and assigns probabilities to the 2 new classes forgetting the older 10 classes. Can you please guide me on this issue ?

**Comment by mtaj** [comment]
terrapattern ka gnd hai

**Comment by aabobakr** [comment]
That's true because the resetClassifier option removes the last layer and adds a new layer based on the new classes you have. The code in this repository doesn't support what you need to do so you have either to train the last layer on the 12 classes again, or edit the code to do what you want !.

**Comment by ahmerlums** [comment]
Ok, can you please enlighten me if it is possible to achieve this. I am relatively new to Machine Learning and Torch.  From what my understanding can summon, I need to go back to the first layer and re-compute the weights based on the new classes. Would it be wise in terms of efficiency(performance and output) to do this ?

**Comment by colesbury** [comment]
@ahmerlums, what you're trying to do is not supported by this project. Good incremental learning is an open problem. See for example, this paper: https://arxiv.org/abs/1611.07725

The standard way to achieve what you want is to retrain on all 12 classes.
