### ISSUE TITLE
bad argument #3 to 'narrow'

### ISSUE THREAD

**Issue by arushk1** [facebook/fb.resnet.torch#14]
th main.lua -retrain resnet-50.t7 -data /data/resnetdata/ -resetClassifier true -nClasses 2

Loading model from file: resnet-50.t7	
 => Replacing classifier with 2-way classifier	
=> Training epoch # 1	
/home/.../torch/install/bin/luajit: ./train.lua:142: bad argument #3 to 'narrow' (out of range at /home/.../torch/pkg/torch/lib/TH/generic/THTensor.c:351)
stack traceback:
	[C]: in function 'narrow'
	./train.lua:142: in function 'computeScore'
	./train.lua:65: in function 'train'
	main.lua:49: in main chunk
	[C]: in function 'dofile'
	...pace/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**Comment by colesbury** [comment]
The code that computes top-5 accuracy doesn't to work with a binary classifier. In the meantime, you can comment out that line in train.lua
