### ISSUE TITLE
Memory leak while saving the checkpoint

### ISSUE THREAD

**Issue by erogol** [facebook/fb.resnet.torch#141]
This code leads to memory bloat after I update torch. Any run ends up killed after couple of epochs but fine without checkpoint function. Particularly deepcopy function causes the problem.

```
function checkpoint.save(epoch, model, optimState, isBestModel, opt)
   -- don't save the DataParallelTable for easier loading on other machines
   if torch.type(model) == 'nn.DataParallelTable' then
      model = model:get(1)
   end

   -- create a clean copy on the CPU without modifying the original network
   model = deepCopy(model):float():clearState()

   local modelFile = 'model_' .. epoch .. '.t7'
   local optimFile = 'optimState_' .. epoch .. '.t7'

   if opt.checkpoint == 'true' then
      model:clearState()
      torch.save(paths.concat(opt.save, modelFile), model)
      torch.save(paths.concat(opt.save, optimFile), optimState)
      torch.save('latest.t7', {
         epoch = epoch,
         modelFile = modelFile,
         optimFile = optimFile,
      })
   end
   if isBestModel then
      model:clearState()
      torch.save(paths.concat(opt.save, 'model_best.t7'), model)
      torch.save(paths.concat(opt.save, 'model_best_optimState.t7'), optimState)
   end
end
```

**Comment by colesbury** [comment]
CPU memory leak or GPU memory?

**Comment by erogol** [comment]
CPU memory

**Comment by flukeskywalker** [comment]
I second this. I have noticed dying runs for the past 2-3 weeks. The OS kills the process due to excessive CPU memory usage. I had not narrowed it down to a checkpoint function issue though.

**Comment by erogol** [comment]
If you disable ``` model = deepCopy(model):float():clearState()``` in checkpoints.lua, it works but I don't know its side effects.

**Comment by meliketoy** [comment]
@erogol The deepCopy function is a function that copies all the model variables into the CPU level, and thus enabling it to conduct clearState() function. The clearState function itself reduces a whole lot of memory of the saved model. However, if you soley conduct the clearState function on the model activated on GPU, it will cause an error.
```
model = model:clearState() # Cannot backpropagate afterwards
```

If you check it, you could see that the model size of the t7 file saved by deepCopy function is within 500MB, while the size of the file save by erasing the code above will actually have a size of more than 3~6GB.

To prevent this, you could conduct this code below,
```bash
model = model:clone():clearState()
```
but, this actually copies the model in the GPU level, so if your model takes up most of your GPU RAM, the program will be facing an 'out of memory' error.

**Comment by colesbury** [comment]
I think this should fix PR should fix the leak:
https://github.com/torch/cutorch/pull/650

(Sorry, I introduced the bug in a cutorch change last month)

**Comment by colesbury** [comment]
If you update "cutorch" this should be fixed now
