### ISSUE TITLE
 My data use Bounding Boxes....... What should I do?

### ISSUE THREAD

**Issue by Bonsen** [facebook/fb.resnet.torch#145]
I see the whole pic is a label in the example, but my data use  Bounding Boxes...? Should I split my own picture into several pictures according to the Bounding Boxes? But the final pictures' size are different.

**Comment by colesbury** [comment]
I don't understand: what do you mean that your data uses bounding boxes? Are you trying to predict bounding boxes? If so, then you should use something like:

https://github.com/rbgirshick/fast-rcnn
