### ISSUE TITLE
File write issue

### ISSUE THREAD

**Issue by arushk1** [facebook/fb.resnet.torch#15]
write error: wrote 2854962 blocks instead of 3211264 at /home/.../torch/pkg/torch/lib/TH/THDiskFile.c:331
stack traceback:
	[C]: in function 'write'
	...ush_Workspace/torch/install/share/lua/5.1/torch/File.lua:201: in function <...ush_Workspace/torch/install/share/lua/5.1/torch/File.lua:107>
	[C]: in function 'write'
	...ush_Workspace/torch/install/share/lua/5.1/torch/File.lua:201: in function 'writeObject'
	...ush_Workspace/torch/install/share/lua/5.1/torch/File.lua:226: in function 'writeObject'
	...orkspace/torch/install/share/lua/5.1/cudnn/Pointwise.lua:67: in function 'write'
	...ush_Workspace/torch/install/share/lua/5.1/torch/File.lua:201: in function 'writeObject'
	...ush_Workspace/torch/install/share/lua/5.1/torch/File.lua:226: in function 'writeObject'
	...ush_Workspace/torch/install/share/lua/5.1/torch/File.lua:226: in function 'writeObject'
	...rush_Workspace/torch/install/share/lua/5.1/nn/Module.lua:150: in function 'write'
	...ush_Workspace/torch/install/share/lua/5.1/torch/File.lua:201: in function 'writeObject'
	...
	...ush_Workspace/torch/install/share/lua/5.1/torch/File.lua:226: in function 'writeObject'
	...ush_Workspace/torch/install/share/lua/5.1/torch/File.lua:226: in function 'writeObject'
	...rush_Workspace/torch/install/share/lua/5.1/nn/Module.lua:150: in function 'write'
	...ush_Workspace/torch/install/share/lua/5.1/torch/File.lua:201: in function 'writeObject'
	...ush_Workspace/torch/install/share/lua/5.1/torch/File.lua:379: in function 'save'
	./checkpoints.lua:37: in function 'save'
	main.lua:62: in main chunk
	[C]: in function 'dofile'
	...pace/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

main.lua is owned by my user.

**Comment by soumith** [comment]
you probably dont have free space on your disk. that's the only plausible explanation that I see.

**Comment by paramsingh96** [comment]
I am getting the following error, when i type: th mainr.lua 
Please help me out with this.

`<csv>	parsing file: data/ans.txt	
<csv>	parsing done	
/home/param/torch/install/bin/lua: /home/param/torch/install/share/lua/5.2/trepl/init.lua:384: /home/param/torch/install/share/lua/5.2/trepl/init.lua:384: /home/param/torch/install/share/lua/5.2/trepl/init.lua:384: /home/param/torch/install/share/lua/5.2/cutorch/init.lua:2: cannot load '/home/param/torch/install/lib/lua/5.2/libcutorch.so'
stack traceback:
	[C]: in function 'error'
	/home/param/torch/install/share/lua/5.2/trepl/init.lua:384: in function 'require'
	./models.lua:92: in function 'resnet'
	mainr.lua:7: in main chunk
	[C]: in function 'dofile'
	...aram/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: in ?
`

**Comment by dingshenglan** [comment]
hello，how did you solve this problem later？
