### ISSUE TITLE
Ensemble modeling

### ISSUE THREAD

**Issue by meliketoy** [facebook/fb.resnet.torch#152]
Hi, I'm a student studying deep learning and I'm currently studying deep residual networks through your code with great interest.
Though, while I was training the model with the imagenet 2012 data, it occurred to me that the best error rate for 5 runs with tenCrop didn't drop below  4.2%, being a little higher than the 3.7% error rate introduced in the original resnet paper.

I figured out that they used an ensemble model with 2 trained resnet 152 models.

I've managed to train 5 of my models with different settings, but couldn't figure how to ensemble them. Is there a particular way to ensemble the model weights in Torch?

Thank you very much for reading this issue :)

**Comment by colesbury** [comment]
I think you can just average the predictions. You could also try learning a weight for each model, but I'm not sure how much that will help.

**Comment by aabobakr** [comment]
You can combine the predictions of the 5 trained models using average ensemble as suggested by @colesbury or voting, which I guess might be better.
