### ISSUE TITLE
Did this project support on cuDNN 3

### ISSUE THREAD

**Issue by samuel1208** [facebook/fb.resnet.torch#16]
Can I train this code with **cuDNN 2**,Because my driver is cuda-6.5. And have not  the permission to update the driver  I found in models/resnet.lua line 154 have following code:
```
if cudnn.version >= 4000 then
    v.bias = nil
    v.gradBias = nil
else
    v.bias:zero()
end
```
1. **Why set v.bias and v.gradBias to nil in cuDNN 4** 
2. **BTW,  Can I train it with cunn**

**Comment by colesbury** [comment]
I have not tested it with cuDNN 2 or cuDNN 3, so it may not work. Please report back if it works for you!

**Comment by colesbury** [comment]
The bias is set to nil because the convolution modules are always followed by SpatialBatchNormalization in ResNet, which means that the bias has no effect. Setting it to nil slightly improves performance.
