### ISSUE TITLE
Port to PyTorch

### ISSUE THREAD

**Issue by panovr** [facebook/fb.resnet.torch#162]
Any plan to port this excellent ResNet implementation to PyTorch?

**Comment by soumith** [comment]
@panovr https://github.com/pytorch/examples/tree/master/imagenet should work fine. We have model definitions and pre-trained models in: https://github.com/pytorch/vision

**Comment by panovr** [comment]
@soumith Great. May I ask does this imagenet example support model re-train and fine-tune? Because this is current lua/torch resnet repo supported and it is very useful for custom data set.
