### ISSUE TITLE
unknown torch class resnet.cifar10dataset not found issue

### ISSUE THREAD

**Issue by karthikgovindasamy** [facebook/fb.resnet.torch#168]

**Comment by karthikgovindasamy** [comment]
can you tell me why the problem is resnet.cifardataset not found is present

**Comment by antoajayraj** [comment]
@colesbury I see a similar problem.. 
th main.lua -depth 50 -batchSize 256 -nGPU 4 -nThreads 8 -shareGradInput true -data /ImageNet2012/
=> Creating model from file: models/resnet.lua
 | ResNet-50 ImageNet
nil
warning: could not load nccl, falling back to default communication
=> Generating list of images
 | finding all validation images
 | finding all training images
 | saving list of images to /ml/fb.resnet.torch/gen/imagenet.t7
FATAL THREAD PANIC: (read) /oasd/torch/share/lua/5.1/torch/File.lua:343: unknown Torch class <resnet.ImagenetDataset>
FATAL THREAD PANIC: (read) /oasd/torch/share/lua/5.1/torch/File.lua:343: unknown Torch class <resnet.ImagenetDataset>
Segmentation fault

Am I missing something basic here ?
