### ISSUE TITLE
unknown Torch class <resnet.ImagenetDataset>

### ISSUE THREAD

**Issue by antoajayraj** [facebook/fb.resnet.torch#169]
I see a similar problem as reported in #168 
th main.lua -depth 50 -batchSize 256 -nGPU 4 -nThreads 8 -shareGradInput true -data /ImageNet2012/
=> Creating model from file: models/resnet.lua
| ResNet-50 ImageNet
nil
warning: could not load nccl, falling back to default communication
=> Generating list of images
| finding all validation images
| finding all training images
| saving list of images to /ml/fb.resnet.torch/gen/imagenet.t7
FATAL THREAD PANIC: (read) /oasd/torch/share/lua/5.1/torch/File.lua:343: unknown Torch class <resnet.ImagenetDataset>
FATAL THREAD PANIC: (read) /oasd/torch/share/lua/5.1/torch/File.lua:343: unknown Torch class <resnet.ImagenetDataset>
Segmentation fault

Am I missing something basic here ? Any help ?

**Comment by colesbury** [comment]
That shouldn't happen. Have you modified the fb.resnet.torch code? Are you running a recent version of Torch?

**Comment by pedropgusmao** [comment]
@antoajayraj Are you using a power8 or any other ppc64le ?

**Comment by antoajayraj** [comment]
@pedropgusmao Yup.. i was using ppc64le.
Now I got it resolved by adding the current directory to LUA_PATH:

$ export LUA_PATH="$LUA_PATH;./?.lua"
$ cd multi-resnet/
$ th main.lua -netType multi-resnet -depth 200 -k 5 -batchSize 64 -nGPU 2 -nThreads 4 -dataset cifar10 -nEpochs 200

Thanks !!
