### ISSUE TITLE
ResNet 152

### ISSUE THREAD

**Issue by yueatsprograms** [facebook/fb.resnet.torch#18]
Hi, it has been almost a month since the blog post was written, has the 152-layer model finished training?
Most importantly, would it be possible to post the convergence plot (val. err. vs. epoch)? That would be very helpful for those who'd like to compare the convergence of your code vs. Kaiming's.

Thanks!

**Comment by colesbury** [comment]
I've added converge plots at https://github.com/facebook/fb.resnet.torch/blob/master/pretrained/CONVERGENCE.md

The 152-layer model finished training, but I believe there was a bug in the changes I had made to train it on 4 GPUs with two half mini-batches of size 128. I will retrain it on 8 GPUs.

**Comment by yueatsprograms** [comment]
Oh wow. So would your bug affect the performance of training the 152 layer models using your github code? (Or does it just affected your particular result since you did an optimization for your system and that was not pushed onto GitHub?)

What I really want to ask is, since I am training 152-layer a model using your code right now with 4 TITAN Xs, should I expect to get the same bug?

**Comment by colesbury** [comment]
No, the bug is not present in the GitHub code. But you probably won't be able to fit 152-layer model on 4 GPUs with batch size 256 without additional code changes.

**Comment by yueatsprograms** [comment]
Right, I can barely train with batch size 128. Thanks for the convergence plots.
