### ISSUE TITLE
What are the settings of pretrained ResNet-101 and ResNet-152 model files?

### ISSUE THREAD

**Issue by wandering007** [facebook/fb.resnet.torch#196]
Are the released pretrained ResNet-101 and ResNet-152 models trained as the full pre-activation variants?

**Comment by colesbury** [comment]
No, only pre-trained ResNet-200 is the pre-activation version.

**Comment by wandering007** [comment]
@colesbury Thanks for the reply, saving my time for downloading and checking them.
