### ISSUE TITLE
multi-gpu work issue

### ISSUE THREAD

**Issue by arBest** [facebook/fb.resnet.torch#2]
Hello,

Great job.

I am able to run the examples (tried only cifar10) fine with single gpu. But when using multi-gpu i get the following error:

th main.lua -dataset cifar10 -batchSize 256 -nGPU 2 -nThreads 8 -backend cudnn -nEpochs 2 -depth 32

/usr/local/torch/install/bin/luajit: ...l/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:217: attempt to compare number with table
stack traceback:
        ...l/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:217: in function 'add'
        ./models/init.lua:90: in function 'setup'
        main.lua:26: in main chunk
        [C]: in function 'dofile'
        ...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x004064d0

Not really sure why though. 

I have trained fine on multiple GPU's before on Tesla k-40's on .https://github.com/soumith/imagenet-multiGPU.torch

Any help would be much appreciated !! Thanks,

**Comment by soumith** [comment]
@arBest try to update your nn and cunn packages

**Comment by arBest** [comment]
@soumith , did as you mentioned.

the above error vanishes, this is what i get now.

/usr/local/torch/install/bin/luajit: bad argument #3 to '?' (number expected, got nil)
stack traceback:
        [C]: at 0x7fb4c641a910
        [C]: in function 'createCudaHostTensor'
        ./train.lua:146: in function 'copyInputs'
        ./train.lua:52: in function 'train'
        main.lua:44: in main chunk
        [C]: in function 'dofile'
        ...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x004064d0

**Comment by colesbury** [comment]
You may also need to update your cutorch package

**Comment by arBest** [comment]
thanks @colesbury . works fine now. thanks @soumith.
