### ISSUE TITLE
Unable to install cudnn bindings on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by tunguz** [facebook/fb.resnet.torch#22]
Hi there,

I've been following the installation process well until I get to the installation of cudnn bindings. When I run

sudo luarocks make

I get the following error message:

Missing dependencies for cudnn:
torch >= 7.0
cutorch 
Error: Could not satisfy dependency: torch >= 7.0

I have run both "luarocks torch" and "luarocks cutorch" commands successfully (although the last one gave me a bunch of warnings). I am using Ubuntu 14.0.4 LTS.

Any ideas what might be causing this?

Thanks,

Bojan

**Comment by colesbury** [comment]
You need to install Torch. See either:
 * https://github.com/facebook/fb.resnet.torch/blob/master/INSTALL.md#install-torch or
 * http://torch.ch/docs/getting-started.html

If you've already installed Torch, then those error messages mean that your path is not set-up properly.  Run `torch-activate` from `~/torch/install/bin/torch-activate`. For more Torch installation help, post in the Torch Google group: https://groups.google.com/forum/embed/?place=forum/torch7#!forum/torch7
