### ISSUE TITLE
the generated model is in a big size

### ISSUE THREAD

**Issue by BrettLL** [facebook/fb.resnet.torch#24]
I retrain the resent-50.t7 on my own data, but the model I have trained is about 6.7G, it is too big, is that regular?? how to reduce the size ?

**Comment by colesbury** [comment]
Load the model, run clearState(), and save the model:

```lua
model = torch.load('model.t7')
model:clearState()
torch.save('model_small.t7', model)
```

**Comment by BrettLL** [comment]
Thanks for your answer, the problem is solved~

**Comment by BrettLL** [comment]
another problem~~  if I clear the model State using model:clearState() in my training procedure, and a small model generated.  Can I use this small one to resume my next epoch?? Or I have to use the big model(about 6.7G) to resume ??  Thanks in advance~~

**Comment by szagoruyko** [comment]
@BrettLL you can use the small one.

**Comment by BrettLL** [comment]
@szagoruyko  Thanks. Then what are the differences between the big and the small one ~~
