### ISSUE TITLE
Bounding box for ImageNet data

### ISSUE THREAD

**Issue by nrajani** [facebook/fb.resnet.torch#25]
I am able to generate probabilities and classes on ImageNet datasets using the ResNet models but I was wondering if there is a way to generate bounding boxes for these images on the object detection dataset.

**Comment by colesbury** [comment]
No, this only includes training code for classification. However, you can use the trained models as a starting point for training a detector.

You might want to try:
https://github.com/fmassa/object-detection.torch/tree/refactoring
https://github.com/andreaskoepf/faster-rcnn.torch

**Comment by Talhasg** [comment]
I have similar but slightly different problem. I have exactly one object in all images (object is same in all given images) and I am trying to predict center of the object. Using resnet model I am able to generate heatmap, but how can I find center of the object?
