### ISSUE TITLE
Feature extraction error

### ISSUE THREAD

**Issue by hiwonjoon** [facebook/fb.resnet.torch#3]
Hi,

When I tried to run feature extraction code as you described, I got an error like below.

```
> th extract-features.lua ../torch_models/resnet-101.t7 ../dataset/attribute/apascal_images/2007_007277.jpg
/home/nine/.torch/install/bin/luajit: ...h/install/share/lua/5.1/nn/SpatialBatchNormalization.lua:82: attempt to index field 'running_std' (a nil value)
stack traceback:
        ...h/install/share/lua/5.1/nn/SpatialBatchNormalization.lua:82: in function 'updateOutput'
        /home/nine/.torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        extract-features.lua:63: in main chunk
        [C]: in function 'dofile'
        ...ine/.torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
```

I confirmed that provided pretrained model have `running_var` parameters which is required at nn.SpatialBatchNormailization, but it doesn't have `running_std`. I also checked `save_mean` and `save_std` parameters, but they doesn't exist, too.

I installed cudnn v4, and Torch bindings@R4. 

Any ideas?

**Comment by soumith** [comment]
hey @hiwonjoon have you updated your nn and cunn packages?
luarocks install nn
luarocks install cunn

I think that will fix things for you

**Comment by colesbury** [comment]
@hiwonjoon did this fix your issue?

**Comment by xcastilla89** [comment]
Hi, I'm not the original poster, but I was having the same issue when fine-tuning the network and this indeed solved it for me.

**Comment by hiwonjoon** [comment]
@soumith @colesbury Updating nn and cunn packages solved the problem. Thanks!
