### ISSUE TITLE
How to implement the random lighting noise in datasets/transforms.lua?

### ISSUE THREAD

**Issue by bryanyzhu** [facebook/fb.resnet.torch#30]
Hi everybody, I was curious how to implement the random lighting noise(alexnet style) in datasets/transforms.lua. Specifically, how to get the pca eigenvalue and vectors for another dataset. like what is the dimension of the input matrix that lead to a 3X3 covariance matrix? Thanks. Any details would do.

**Comment by colesbury** [comment]
IIRC, you take a Tensor of size Nx3 and where N is all the pixels from a given channel (R/G/B) from lots of images.

Also, I found that this Alexnet style noise didn't seem to help.

**Comment by bryanyzhu** [comment]
@colesbury Thanks a lot, that's also the way I think, but I will still try to see if it helps.
