### ISSUE TITLE
The classifier result of ResNet-200

### ISSUE THREAD

**Issue by wlw208dzy** [facebook/fb.resnet.torch#33]
Hi, Sam! Thanks for sharing your pretrained model of ResNet-200, but when I used the model to implement the classification test of ILSVRC2012_val_00000001.JPEG(Ground Truth is Sea Snake), the result seems to be wrong as shown below:

0.3930911719799          reflex camera 
0.30106797814369        marimba, xylophone
0.10095628350973        convertible
0.076501801609993      ruddy turnstone, Arenaria interpres
0.067097567021847      giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca

I have also used resnet-101.t7 before, the classification is just right:

0.52688080072403        sea snake
0.2866522371769          rock python, rock snake, Python sebae
0.073128215968609       hognose snake, puff adder, sand viper
0.048126801848412       water snake
0.021316176280379       Indian cobra, Naja naja

So I don't know why the model **resnet-101.t7** will have a right result for classification while **resnet-200.t7** not. Would you please tell me if there are some differences for **preprocessing the dataset**?

**Comment by leonardoaraujosantos** [comment]
I'm having the same problem :(

**Comment by gcr** [comment]
I agree. Calling `trainer:test(0, valLoader)` with the loaded model results in 99.9% error (ie. no better than chance). Something seems to be fishy with this model, or maybe I'm loading it wrong...?

**Comment by colesbury** [comment]
Sorry -- I messed up and originally upload a model with the a different ordering of classes. On Friday, I fixed the decoder and re-uploaded the model. Can you try downloading the model again?

On ILSVRC2012_val_00000001.JPEG I get:
0.39309191703796        sea snake
0.30106738209724        water snake
0.1009563729167 rock python, rock snake, Python sebae
0.076501652598381       Indian cobra, Naja naja
0.067097559571266       hognose snake, puff adder, sand viper

**Comment by wlw208dzy** [comment]
Thanks for your reply @colesbury . I downloaded the model just now and made a classfication test again.   Result is right! The other thing I want to ensure is: data-preprocessing for resnet-200.t7 is the same as resnet-101.t7 or not?

**Comment by leonardoaraujosantos** [comment]
Yes now is working :)

**Comment by colesbury** [comment]
@wlw208dzy, data preprocessing is the same
