### ISSUE TITLE
8.5 GB models

### ISSUE THREAD

**Issue by pedropgusmao** [facebook/fb.resnet.torch#38]
Hi, 
Is there a way to "clean" models before storing them. Models (resnet-34) are currently taking 8.5 GB after each epoch of training.

**Comment by Cadene** [comment]
You can try this function to clean your models before saving same.

`
local sanitize = function (net)
   local list = net:listModules()
   for _,val in ipairs(list) do
      for name,field in pairs(val) do
         if torch.type(field) == 'cdata' then val[name] = nil end
         if (name == 'output' or name == 'gradInput') then
            val[name] = field.new()
         end
      end
   end
end

sanitize(net)
torch.save('net.t7',net)
`

**Comment by szagoruyko** [comment]
@Cadene @pedropgusmao don't do that. Call `model:clearState()` before saving the model.

**Comment by pedropgusmao** [comment]
Thanks, but will that prevent me from correctly continuing training later on if I am using momentum (and hence need previous gradients)?

**Comment by szagoruyko** [comment]
@pedropgusmao momentum is stored in optimState which should be saved separately. you can safely continue from clearState checkpoints.
