### ISSUE TITLE
threads dojob waiting forever

### ISSUE THREAD

**Issue by ouceduxzk** [facebook/fb.resnet.torch#44]
Hi, I have a problem that when I try to run the code twice, it runs one time and works perfect. however, when i ran another, in the dataloader.lua, the dojob can not be finished and the whole system is waiting. Any idea why this happens?

**Comment by colesbury** [comment]
I'm not sure I understand. Are you running the two training runs at the same time?

**Comment by ouceduxzk** [comment]
no, run one finished and then run next one, it's sequentially

**Comment by colesbury** [comment]
If you run it again, does it hang?

**Comment by ouceduxzk** [comment]
yes, so far I tracked the problem down to the  #99line in dataloader.lua       threads:dojob().

**Comment by ouceduxzk** [comment]
this is perculiar since I run the code multiple times before and no problem. However, recently I have some library install and delete and environment change, which might have a influence on the low level thread library ?

**Comment by colesbury** [comment]
Maybe there's an error loading the data that's getting hidden by the threads. I'd be surprised if the issue is actually in the threads library (as opposed to just being hidden by the multi-threading)

**Comment by ouceduxzk** [comment]
what's the best way to debug the dataloader ?  Right now, I print everything out to see which is not working.

Thanks

**Comment by colesbury** [comment]
Make it single-threaded:
- Get rid of the body of [`loop()`](https://github.com/facebook/fb.resnet.torch/blob/master/dataloader.lua#L95-L105)
- Replace that with the actual [data loading code](https://github.com/facebook/fb.resnet.torch/blob/master/dataloader.lua#L63-L81)

**Comment by ouceduxzk** [comment]
Thanks, man, will try it laters

**Comment by ljk628** [comment]
Try setting OMP_NUM_THREADS=1? This helps me solving https://github.com/facebook/fb.resnet.torch/issues/17.

**Comment by ouceduxzk** [comment]
thanks guys, actually reinstall torch and cutorch fix the problem, I do not know what happened exactly, but I learned something through this problem. 

Thank you

**Comment by arthitag** [comment]
I faced a similar problem. My training code was just hanging(not showing any progress on the terminal) although the GPU memory was occupied. The GPU temperature was low(indicating inactivity). It was a multi-GPU model training with multi-threaded data loading. I faced the problem even when I tried the code on a single GPU and set the number of threads to 1. 
I was getting a warning from DataparallelTable.lua that it coudn't load nccl(in the multi-GPU training). I installed nccl and also updated torch,cutorch,nn and cunn. None of this however resolved the issue. 
I had to ultimately follow the suggestion of @colesbury and replace the code in the dataloader.loop() with the dataloading code. This seems to have resolved the issue and I don't see the freezing thing happening any more. Thanks! I hope someone else finds this useful.
