### ISSUE TITLE
backend for BN and MaxPooling

### ISSUE THREAD

**Issue by ljk628** [facebook/fb.resnet.torch#5]
Hi, is there any reason why the backend for Max and SBatchNorm is not cudnn? 
```lua
local Max = nn.SpatialMaxPooling
local SBatchNorm = nn.SpatialBatchNormalization
```
Is that because the cudnn layers are not stable yet? It seems to me changing above modules to cudnn version has  a 1.27x speedup over nn version for a minibatch of 128 on CIFAR10 and gets almost the same accuracy.

**Comment by colesbury** [comment]
At the time this was released the `nn.SpatialBatchNormalization` implementation was about 50% faster than `cudnn.SpatialBatchNormalization` on ImageNet, and the variance calculation was more numerically stable. I think the `cudnn.SpatialBatchNormalization` has been improved in the latest release of cuDNN, and may now be faster than the NN implementation, but I haven't tested it yet.

The cuDNN implementation of SpatialMaxPooling is not deterministic, while the NN implementation is. I don't think there's a noticeable performance difference between the two.

**Comment by ljk628** [comment]
Thanks for the clarification!
