### ISSUE TITLE
ResNet training hangs at random iter

### ISSUE THREAD

**Issue by Fchaubard** [facebook/fb.resnet.torch#52]
On a screen session, I run:

th main.lua -depth 18 -batchSize 128 -nGPU 1 -nThreads 1  -data ../imagenet/

and then detach. Everything is going well until the training just pauses at some random iter.

 | Epoch: [1][677/10010]    Time 3.408  Data 3.266  Err 6.4433  top1 100.000  top5  96.875
 | Epoch: [1][678/10010]    Time 3.152  Data 3.008  Err 6.5600  top1  98.438  top5  97.656
 | Epoch: [1][679/10010]    Time 3.664  Data 3.518  Err 6.5425  top1 100.000  top5  97.656
 | Epoch: [1][680/10010]    Time 3.195  Data 3.051  Err 6.5057  top1 100.000  top5  96.875
 | Epoch: [1][681/10010]    Time 4.066  Data 3.923  Err 6.3842  top1  98.438  top5  96.875
 | Epoch: [1][682/10010]    Time 3.740  Data 3.595  Err 6.5573  top1 100.000  top5  98.438
 | Epoch: [1][683/10010]    Time 3.562  Data 3.418  Err 6.4775  top1 100.000  top5  96.875
 | Epoch: [1][684/10010]    Time 3.370  Data 3.228  Err 6.5334  top1  98.438  top5  96.094
 | Epoch: [1][685/10010]    Time 3.494  Data 3.349  Err 6.2895  top1  98.438  top5  94.531
 | Epoch: [1][686/10010]    Time 4.154  Data 3.987  Err 6.4592  top1  98.438  top5  96.875
 | Epoch: [1][687/10010]    Time 3.143  Data 2.985  Err 6.4096  top1  98.438  top5  95.312
 | Epoch: [1][688/10010]    Time 3.350  Data 3.187  Err 6.5375  top1 100.000  top5  98.438
 | Epoch: [1][689/10010]    Time 3.549  Data 3.388  Err 6.5928  top1 100.000  top5  95.312
 | Epoch: [1][690/10010]    Time 3.538  Data 3.396  Err 6.4876  top1  98.438  top5  96.875
 | Epoch: [1][691/10010]    Time 3.228  Data 3.079  Err 6.4927  top1  99.219  top5  95.312
 | Epoch: [1][692/10010]    Time 3.842  Data 3.687  Err 6.4195  top1  98.438  top5  96.094
 | Epoch: [1][693/10010]    Time 3.866  Data 3.723  Err 6.5156  top1  98.438  top5  97.656
 | Epoch: [1][694/10010]    Time 3.428  Data 3.279  Err 6.3716  top1  96.875  top5  92.969
 | Epoch: [1][695/10010]    Time 3.550  Data 3.408  Err 6.4982  top1 100.000  top5  97.656

This has happened 4 times now at different iters. Tried varying the number of threads / gpu / batchsize / etc. For example:

th main.lua -depth 18 -batchSize 256 -nGPU 3 -nThreads 8 -shareGradInput true -data /mnt/hdd1/resnet_torch/imagenet/

stopped at  Epoch: [2][113/505]

**Cuda version:**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

**cudnn version:**
cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR      4
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 7

**Ubuntu version:**
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

and I have 3 titan X's without anything else running on them that are correctly setup (have run many caffe/torch jobs before).

**Comment by colesbury** [comment]
The "Data" column is the data loading time. It's really high in your output. It should be close to zero, since data is loaded in the background.

Is the ImageNet data on a SSD?

**Comment by gcr** [comment]
It could be super helpful to give us a backtrace when the process hangs. That way, we can see what it's getting stuck on.

Could you run `gdb -p (the process ID of luajit)` and send us the output of the `thread apply all backtrace` command?

**Comment by colesbury** [comment]
You're welcome to re-open the issue with more details (like a backtrace)
