### ISSUE TITLE
What's the meaning of following statements?

### ISSUE THREAD

**Issue by ajeetksingh** [facebook/fb.resnet.torch#57]
I noticed these statements in `models/resnet.lua` file. I know that these are used for the initializing the 
respective layers. Can anyone please tell me the individual significance of the following statements?
It seems that, only one of them get executed at any given time.

`  ConvInit('cudnn.SpatialConvolution')`
   `ConvInit('nn.SpatialConvolution')`
  ` BNInit('fbnn.SpatialBatchNormalization')`
   `BNInit('cudnn.SpatialBatchNormalization')`
   `BNInit('nn.SpatialBatchNormalization')`

Thanks.

**Comment by colesbury** [comment]
They initialize the weights and biases the respective modules. They're defined in the same file in which they are used.

**Comment by ajeetksingh** [comment]
That is correct. But my question was, why only one of them get executed? 
To test this, I wrote the initial weights in a file. But I found that only `ConvInit('cudnn.SpatialConvolution')` get executed not the `ConvInit('nn.SpatialConvolution')`.

Thanks.

**Comment by soumith** [comment]
you could run the code in a debugger and trace line by line and figure it out.

**Comment by ajeetksingh** [comment]
Silly me, now I get it.
Thanks anyways. :)
