### ISSUE TITLE
Problem while accessing the activation outputs of intermediate layers.

### ISSUE THREAD

**Issue by ajeetksingh** [facebook/fb.resnet.torch#58]
Hi, 

I am trying to dump the activation output of every layer in a file, for 
sanity checking.
So, in `train.lua`, we pass a minibatch to the model in following way:

`local output = self.model:forward(self.input):float()`
which gives me the output of size `128x10`, which I presume to be the output of the last layer. `128` being the minibatch size.

Is there any way I can get the outputs of the intermediate layers?

Thanks.

**Comment by colesbury** [comment]
You can get intermediate layers using `self.model:get(n)`. You can get the output from a layer using `layer.output`. So something like:

```lua
self.model:forward(self.input)
local output = self.model:get(i):get(j).output
```

**Comment by ajeetksingh** [comment]
Thanks for the swift reply, @colesbury 
But I am finding it difficult to get the activations on per image basis. For example, 
I have a minibatch of size `128x3x32x32 (self.input)`. The first layer is a 
`cudnn.SpatialConvolution(3 -> 16, 3x3, 1,1, 1,1)`

`self.model:forward(self.input)`
`local output = self.model:get(1):get(1).output`
It will give the output of the first layer, which is coming out to be of size `64x16x32x32`. How do I decipher the activation for each image?

Thanks.

**Comment by sheikirfanbasha** [comment]
@ajeetksingh Hi Ajeet, Did you find the answer by any chance? If so, please post it here.

**Comment by ajeetksingh** [comment]
Run the code on single GPU instead of running on multiple GPUs. This way, all the images in the batch would be accessible.

'self.model:forward(self.input)'
`local output = self.model:get(1):get(1).output`
