### ISSUE TITLE
Multi-GPU Hanging With More than 2 GPUs

### ISSUE THREAD

**Issue by stephenrawls** [facebook/fb.resnet.torch#62]
Hi,

I am trying to use this code for training an MS-ResNet 101-layer model. I am running into trouble with the multi-GPU feature. I am able to successfully train models using 2 GPU's without a problem, but as soon as I move to 3 or more GPU's I am unable to train--the behavior is that after finishing the first mini-batch the program just hangs. (I have tried with nGPU=3,4,5,6,7,8).

I have a machine with 8 Titan-X GPUs, and it would greatly speed up training if I could make use of all 8 GPUs.

I have updated all relevant dependencies: nn, cunn, cudnn, torch, torch.nccl, but I still have the same problem.

I am able to assist in debugging this, but my experience with low-level GPU programming is quite limited. Any suggestions for things to try would be appreciated.

Thanks,
Stephen

**Comment by colesbury** [comment]
Do the test_DataParalllelTable.lua (from https://github.com/torch/cunn) tests pass?

**Comment by stephenrawls** [comment]
Hi @colesbury -- Thanks for the pointer, it looks like these tests are failing. I guess I should go open an issue at torch/cunn now?

```
% th <snip>/install/share/lua/5.1/cunn/test_DataParallelTable.lua
Running 13 tests
 1/13 DataParallelTable_emptyTensor ..................................... [ERROR]
 2/13 DataParallelTable_noGradInput ..................................... [ERROR]
 3/13 DataParallelTable_misc ............................................ [PASS]
 4/13 DataParallelTable_serialize ....................................... [ERROR]
 5/13 DataParallelTable_type ............................................ [PASS]
 6/13 ProfileDataParallelTable .......................................... [WAIT]
Profiling DataParallelTable with 1 gpus   
  Time per FPROP+BPROP: 0.36483557224274  
Profiling DataParallelTable with 2 gpus   
  Time per FPROP+BPROP: 0.6190810918808   
Profiling DataParallelTable with 3 gpus   
  Time per FPROP+BPROP: 0.53080530166626  
Profiling DataParallelTable with 4 gpus   
  Time per FPROP+BPROP: 0.5239892244339   
Profiling DataParallelTable with 5 gpus   
 6/13 ProfileDataParallelTable .......................................... [ERROR]
 7/13 DataParallelTable_sync ............................................ [ERROR]
 8/13 DataParallelTable_emptyData ....................................... [FAIL]
 9/13 DataParallelTable_streams ......................................... [WAIT]
```

(I had to kill the test because the last one was just hanging)

Thanks,
Stephen

**Comment by colesbury** [comment]
Yeah, I think that makes sense. You might also want to just try reinstalling torch from scratch to see if that helps

**Comment by colesbury** [comment]
Just checked on my machine. The DataParallelTable_noGradInput is failing but the other tests should pass.

**Comment by stephenrawls** [comment]
Ok, will do. Thanks for the help!
