### ISSUE TITLE
Multiple GPU support Problem

### ISSUE THREAD

**Issue by MissT157** [facebook/fb.resnet.torch#71]
Hi,

I recently started working on the code and wanted to use it over multiple GPUs.
The server I am working on has 5 GPUs but, as I have been assigned only two of those, I want to limit it on just those two. But no matter what is the nGPU flag, the code runs on all 5.

Is it a problem of the code, or something inherent in torch. If just the code, could you suggest a way to fix the issue?

Thanks.

**Comment by colesbury** [comment]
Use e.g. `CUDA_VISIBLE_DEVICES=0,1 th main.lua ...` to run on the first two GPUs

**Comment by MissT157** [comment]
Awesome, it works!!

Thank you.

**Comment by jaewoosong** [comment]
Thank you!
