### ISSUE TITLE
Normalization params for custom dataset?

### ISSUE THREAD

**Issue by siddhu95** [facebook/fb.resnet.torch#72]
I plan to run it on a custom dataset and I have managed to train it.But now when I want to access the norm params using which it was trained, where do I look for it.Also can u guide me on how to test with 10 crop averaging?

**Comment by colesbury** [comment]
Check https://github.com/facebook/fb.resnet.torch/blob/master/datasets/imagenet.lua#L67-L78 for image normalization parameters.

Use `-tenCrop true` to evaluate with ten crops
