### ISSUE TITLE
Multi GPU query

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [facebook/fb.resnet.torch#73]
Hi,

Does the GPUs on which you train be consecutive? I'm working on a system with 16GPUs, when I train on consecutive GPUs (say 1,2), the training starts, but when I train on GPUs (say 1,7) then I'm getting an error. 
Does the communication between GPUs happen only between consecutive GPUs?

**Comment by soumith** [comment]
You likely do not have all gpus with p2p access. So some combinations of gpus wont work. However, this has nothing to do with that numbering of gpus.

http://on-demand.gputechconf.com/gtc-express/2011/presentations/cuda_webinars_GPUDirect_uva.pdf

**Comment by akileshbadrinaaraayanan** [comment]
Hi Soumith, Thanks for your response. 

I'm trying this way 
CUDA_VISIBLE_DEVICES=1,13  th main.lua -dataset cifar10 -batchSize 128 -depth 20 -nGPU 2
and in models/init.lua file, I change the local gpus variable from torch.range(1, opt.nGPU):totable() to torch.totable(torch.Tensor({1,13})) .

I'm getting an error "invalid device ordinal".

However, CUDA_VISIBLE_DEVICES=1,2  th main.lua -dataset cifar10 -batchSize 128 -depth 20 -nGPU 2  and in models/init.lua file, I retain the local gpus variable as torch.range(1, opt.nGPU):totable() , then the code works.

Will the above link solve this problem? Thanks in advance.

**Comment by colesbury** [comment]
Do you have 14 GPUs?

1) CUDA_VISIBLE_DEVICES is zero indexed
2) You probably don't want to change `torch.range(1, opt.nGPU):totable()`. If you use, for example, CUDA_VISIBLE_DEVICES=0,3 then the process will see two GPUs, which will be index in torch as {1, 2}.

**Comment by akileshbadrinaaraayanan** [comment]
Thanks Sam, that solved the problem.
