### ISSUE TITLE
Fitting of the Model Over multiple GPUs

### ISSUE THREAD

**Issue by MissT157** [facebook/fb.resnet.torch#74]
Hi,
For the training of resnet, I am trying to train a 101 layer model (at least) on Tesla K80s. 
But, even with a batch size of just 50, on a 50 layer model I am falling out of memory while training over 4 Tesla K80s.
I refuse to believe that 4 K80s are insufficient for such a run.

Some more information regarding the run, my image size of the input is 448x448 and for a batchsize of 32, it works.

I would love to get some insight into this. 

Thanks.

**Comment by colesbury** [comment]
Use `-shareGradInput true` if you aren't already.
https://github.com/facebook/fb.resnet.torch/blob/master/TRAINING.md#sharegradinput
