### ISSUE TITLE
No longer shareGradInput after the first epoch if nGPU > 1

### ISSUE THREAD

**Issue by Cysu** [facebook/fb.resnet.torch#82]
When nGPU > 1 and shareGradInput = true, it is observed that the memory consumption of resnet-101 increases from ~5GB to ~10GB after the first epoch (deeper nets will be out of memory).

It seems that [this line](https://github.com/facebook/fb.resnet.torch/blob/master/checkpoints.lua#L34) of code leads to the problem. The later `models.shareGradInput(model)` only changes the local variable `model` instead of the global one.

**Comment by colesbury** [comment]
Oops, thanks for catching this

**Comment by zacurr** [comment]
I got same problem. With 4 Titan-X, 50-layer resnet training with batchsize = 256 has out of memory error on 2nd epoch.
How can I resolve this?

Finished epoch # 1     top1:  89.039  top5:  71.766

 * Best model     89.039042853151    71.76569207712    
=> Training epoch # 2    
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-1397/cutorch/lib/THC/generic/THCStorage.cu line=40 error=2 : out of memory
/opt/torch/install/bin/luajit: /opt/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] /opt/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 5 module of nn.Sequential:
In 3 module of nn.Sequential:
In 1 module of nn.Sequential:
In 1 module of nn.ConcatTable:
In 1 module of nn.Sequential:
...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:386: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-1397/cutorch/lib/THC/generic/THCStorage.cu:40
stack traceback:
    [C]: in function 'resizeAs'
    ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:386: in function 'updateGradInput'
    /opt/torch/install/share/lua/5.1/nn/Module.lua:31: in function </opt/torch/install/share/lua/5.1/nn/Module.lua:29>
    [C]: in function 'xpcall'
    /opt/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /opt/torch/install/share/lua/5.1/nn/Sequential.lua:88: in function </opt/torch/install/share/lua/5.1/nn/Sequential.lua:78>
    [C]: in function 'xpcall'
    /opt/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /opt/torch/install/share/lua/5.1/nn/ConcatTable.lua:66: in function </opt/torch/install/share/lua/5.1/nn/ConcatTable.lua:30>
    [C]: in function 'xpcall'
    ...
    /opt/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function </opt/torch/install/share/lua/5.1/nn/Sequential.lua:78>
    [C]: in function 'xpcall'
    /opt/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    /opt/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function </opt/torch/install/share/lua/5.1/nn/Sequential.lua:78>
    [C]: in function 'xpcall'
    /opt/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
    /opt/torch/install/share/lua/5.1/threads/queue.lua:65: in function </opt/torch/install/share/lua/5.1/threads/queue.lua:41>
    [C]: in function 'pcall'
    /opt/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
    [string "  local Queue = require 'threads.queue'..."]:13: in main chunk

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
    [C]: in function 'error'
    /opt/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
    /opt/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function </opt/torch/install/share/lua/5.1/nn/Sequential.lua:78>
    [C]: in function 'xpcall'
    /opt/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
    /opt/torch/install/share/lua/5.1/threads/queue.lua:65: in function </opt/torch/install/share/lua/5.1/threads/queue.lua:41>
    [C]: in function 'pcall'
    /opt/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
    [string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
    [C]: in function 'error'
    /opt/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
    /opt/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
    /opt/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:725: in function 'exec'
    /opt/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:232: in function 'backward'
    ./train.lua:62: in function 'train'
    main.lua:49: in main chunk
    [C]: in function 'dofile'
    /opt/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

**Comment by colesbury** [comment]
This should be fixed now if you `git pull`
