### ISSUE TITLE
Large Memory Consumption When fine-tuning with sharegradInput=true option

### ISSUE THREAD

**Issue by zacurr** [facebook/fb.resnet.torch#85]
When training imagenet dataset from scratch 
with depth=50, batchsize=256, nGPU=4, shareGradInput=true,
Memory usage was 7.1~7.4GB per GPU

When using retrain option while keep other options same (nGPU, batchSize , shareGradInput and etc),
Memory usage was 10~11GB per GPU in first epoch, and increased about 0.7~1.3GB on 2nd epoch, 
and on third epoch, "out of memory" occured. (I use 4 Titan X which has 12GB memory) 
(Of course, with sharegradinput = false , "out of memory" occured in first epoch)

This is not related to the issue, https://github.com/facebook/fb.resnet.torch/issues/82
I used the latest commit which fixed the sharegradinput problem in second epoch.

The memory-usage gap between two case was 3~4 GB per GPU.

The following is the option that i used.
I didn't use resetClassifier option, because I fine-tune the model on same imagenet dataset (I changed scale augmentation method on my own way, but this does not impact on memory-usage when training from scratch. Even though I use original code, the same thing happened)

th main.lua -retrain /home/ubuntu/resnet-50.t7 -data /home/ubuntu/ILSVRC2015/Data/CLS-LOC -shareGradInput true -nThreads 24 -nGPU 4 -batchSize 256 -LR 0.001 

How can this problem be resolved?
Help me plz!

**Comment by colesbury** [comment]
I just merged #66, which improves checkpointing. Please pull and try again.

**Comment by zacurr** [comment]
Prior to this merge, I  merged #66 into previous commit on my own and found it works very well.
Memory-usage is stable and not increased according to epochs.

* original code in #66 produces overflow error.
With very simple modification on " local function saveModel(m)" in #66, it was resolved


Even though I didn't test the latest commit, I think it will resolve this issue.
Thank you very much !
