### ISSUE TITLE
How to save a model created by nngraph?

### ISSUE THREAD

**Issue by bearpaw** [facebook/fb.resnet.torch#95]
Hi all,

When created with nngraph, the [deepcopy](https://github.com/facebook/fb.resnet.torch/blob/1eaabeb2ec7bb4e41ff18f4b5971e893832f140e/checkpoints.lua#L51) will cause the **out of memory** error.

If I save the model with `clearState` without deepcopy, the training crashed after several epochs:
```sh
/home/xxx/torch/install/bin/luajit: /home/xxx/torch/install/share/lua/5.1/threads/threads.lua:183: 
[thread 1 callback] ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:376: attempt to perform arithmetic on a nil value
```

Does anyone have any suggestions? Thanks in advance!

**Comment by bestlin** [comment]
Have you solved this problem?

**Comment by bearpaw** [comment]
@bestlin I just save the model without `deepcopy` and without `clearState`. Everything works fine for me.
